<?php
// This file is automatically generated. Don't make manual changes as they will get overwritten when you republish your website.
$_SETTINGS = [
	"to"						=> "wkuling@gmail.com",							// To Address
	"toAlt"						=> "",						// Additional Recipients
	"from"						=> "wkuling@gmail.com",						// From Address
	"fromName"					=> "Je website",					// From Name
	"fromThem"					=> "0",					// Use Sender as From Address
	"fromThemReplyTo"			=> "1",			// Use Sender as Reply-To
	"fromNameThem"				=> "1",				// Use Sender Name as From Name
	"fromNameThemField"			=> "{name}",		// Name of the field(s) that can contain the Sender Name
	"template"					=> "Hi Jorinde,<br><br>Je hebt een nieuw bericht ontvangen vanuit je website.<br><br>{formdata}<br><br>Date: {date}<br>Remote IP: {ip}<br><br>---<br>Mooie dag toegewenst!",					// Mail Template
	"dateFormat"				=> "F j, Y",					// Date format
	"timeFormat"				=> "g:i a",					// Time format
	"autorespondSubjectPrefix"	=> "Re:",	// Autorespond Form Subject Prefix
	"autorespondSubject"		=> "",			// Autorespond Custom Subject
	"autorespondTemplate"		=> "Hi {name},<br><br>Thank you for your message. We'll get back to you as soon as we can.<br>Here's the information you sent us:<br><br>{formdata}<br><br>---<br>Have a nice day.",		// Autorespond Template
	"rcp"						=> "0",					// Use reCAPTCHA
	"rcpVersion"				=> "3",			// reCAPTCHA Version
	"rcpScore"					=> "0.5",				// reCAPTCHA Score
	"rcpSecret"					=> "",			// reCAPTCHA Secret Key
	"smtp"						=> "1",						// Use SMTP
	"smtpDebug"					=> "0",					// SMTP Debug
	"smtpHost"					=> "smtp.gmail.com",					// SMTP Host
	"smtpPort"					=> "587",					// SMTP Port
	"smtpSecure"				=> "tls",					// SMTP Use SSL/TLS (empty, ssl or tls)
	"smtpUsername"				=> "wkuling@gmail.com",				// SMTP Username
	"smtpPassword"				=> "hnkjwhmshzhyecuv",				// SMTP Password
	"attachmentsExtensions"		=> "avi,bmp,cer,cfg,css,csv,cur,doc,docx,eml,emlx,fnt,fon,gif,h264,ico,ini,jpeg,jpg,key,log,mid,mkv,mov,mp3,mp4,mpa,mpeg,mpg,msg,odp,ods,odt,ogg,otf,pdf,png,pps,ppt,pptx,ps,psd,rss,rtf,svg,tif,tiff,ttf,txt,vcf,wav,webm,webp,wma,wmv,wpd,xls,xlsx",		// File Extensions
	"attachmentsMimeTypes"		=> "application/gzip,application/java-archive,application/json,application/ld+json,application/msword,application/ogg,application/pdf,application/rtf,application/vnd.amazon.ebook,application/vnd.api+json,application/vnd.apple.installer+xml,application/vnd.mozilla.xul+xml,application/vnd.ms-excel,application/vnd.ms-fontobject,application/vnd.ms-powerpoint,application/vnd.oasis.opendocument.presentation,application/vnd.oasis.opendocument.spreadsheet,application/vnd.oasis.opendocument.text,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.rar,application/vnd.visio,application/x-7z-compressed,application/x-abiword,application/x-bzip,application/x-bzip2,application/x-freearc,application/x-httpd-php,application/x-tar,application/x-www-form-urlencoded,application/xhtml+xml,application/xml,application/zip,application/zstd,audio/*,font/*,image/*,multipart/form-data,text/plain,text/calendar,text/css,text/csv,text/rtf,video/*",		// Mime Types
	"allowedHTML"				=> "b,br,i,p,u"					// Allowed HTML Tags (BB)
];
?>